use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::Command,
    time::Duration,
};

use anyhow::{Context, Result, bail};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::session::{SessionBackend, SessionConfig, SessionManager, WaitCondition};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DemoOptions {
    pub root: PathBuf,
    pub name: String,
    pub shell: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DemoSummary {
    pub status: String,
    pub session_id: String,
    pub run_dir: PathBuf,
    pub workspace: PathBuf,
    pub log_dir: PathBuf,
    pub event_log_path: PathBuf,
    pub proof_json_path: PathBuf,
    pub proof_markdown_path: PathBuf,
    pub proof_html_path: PathBuf,
    pub report_path: PathBuf,
    pub screen_tail: String,
}

pub fn run_demo(options: DemoOptions) -> Result<DemoSummary> {
    let session_id = safe_component(&options.name);
    let run_dir = options.root.join(format!(
        "{}-{}-{}",
        session_id,
        Utc::now().format("%Y%m%d-%H%M%S"),
        Uuid::new_v4()
            .simple()
            .to_string()
            .get(..8)
            .unwrap_or("run")
    ));
    let workspace = run_dir.join("workspace");
    let log_dir = run_dir.join("logs");
    fs::create_dir_all(&workspace)
        .with_context(|| format!("create demo workspace {}", workspace.display()))?;

    write_demo_workspace(&workspace)?;
    init_demo_git(&workspace)?;

    let manager = SessionManager::new(&log_dir)?;
    manager.open(SessionConfig {
        id: session_id.clone(),
        workspace: workspace.clone(),
        shell: options.shell,
        env: BTreeMap::new(),
        rows: 24,
        cols: 100,
        backend: SessionBackend::Pty,
    })?;

    let result = run_demo_session(&manager, &session_id);
    let _ = manager.kill(&session_id);
    let proof = result?;

    let report_path = run_dir.join("demo-report.md");
    fs::write(
        &report_path,
        render_demo_report(&proof.screen_tail, &proof.markdown_path, &proof.html_path),
    )
    .with_context(|| format!("write demo report {}", report_path.display()))?;

    Ok(DemoSummary {
        status: "ok".to_string(),
        session_id,
        run_dir,
        workspace,
        log_dir,
        event_log_path: proof.log_path,
        proof_json_path: proof.json_path,
        proof_markdown_path: proof.markdown_path,
        proof_html_path: proof.html_path,
        report_path,
        screen_tail: proof.screen_tail,
    })
}

fn run_demo_session(
    manager: &SessionManager,
    session_id: &str,
) -> Result<crate::session::ProofBundle> {
    manager.send_line(session_id, "sh ./check.sh || true")?;
    manager.wait(
        session_id,
        WaitCondition::Regex {
            pattern: "demo checks failed".to_string(),
        },
        Duration::from_secs(10),
    )?;

    manager.send_line(
        session_id,
        "printf 'fixed\\n' > answer.txt && sh ./check.sh && echo agent-pty-demo-success",
    )?;
    manager.wait(
        session_id,
        WaitCondition::Regex {
            pattern: "agent-pty-demo-success".to_string(),
        },
        Duration::from_secs(10),
    )?;

    manager.proof(session_id)
}

fn write_demo_workspace(workspace: &Path) -> Result<()> {
    fs::write(
        workspace.join("README.md"),
        "# agent-pty demo workspace\n\nThis repository is generated by `agent-pty demo`.\n",
    )
    .with_context(|| format!("write {}", workspace.join("README.md").display()))?;
    fs::write(workspace.join("answer.txt"), "broken\n")
        .with_context(|| format!("write {}", workspace.join("answer.txt").display()))?;
    fs::write(
        workspace.join("check.sh"),
        r#"#!/bin/sh
set -eu
if [ "$(cat answer.txt)" = "fixed" ]; then
  echo "demo checks passed"
else
  echo "demo checks failed"
  exit 1
fi
"#,
    )
    .with_context(|| format!("write {}", workspace.join("check.sh").display()))?;
    Ok(())
}

fn init_demo_git(workspace: &Path) -> Result<()> {
    run_git(workspace, &["init"])?;
    run_git(workspace, &["add", "."])?;
    run_git(
        workspace,
        &[
            "-c",
            "user.name=agent-pty demo",
            "-c",
            "user.email=agent-pty-demo@example.test",
            "commit",
            "-m",
            "demo baseline",
        ],
    )?;
    Ok(())
}

fn run_git(workspace: &Path, args: &[&str]) -> Result<()> {
    let output = Command::new("git")
        .args(args)
        .current_dir(workspace)
        .output()
        .with_context(|| format!("run git {}", args.join(" ")))?;
    if !output.status.success() {
        bail!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(())
}

fn render_demo_report(screen_tail: &str, proof_path: &Path, proof_html_path: &Path) -> String {
    format!(
        "# agent-pty demo\n\nagent-pty demo complete\n\n- proof: {}\n- proof html: {}\n\n## Screen Tail\n\n```text\n{}\n```\n",
        proof_path.display(),
        proof_html_path.display(),
        screen_tail.trim_end()
    )
}

fn safe_component(value: &str) -> String {
    let safe = value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>();
    let safe = safe.trim_matches('-');
    if safe.is_empty() {
        "demo".to_string()
    } else {
        safe.to_string()
    }
}
